/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 CP1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "AD_konverter.h"
#include "Pin_Voltage_aliases.h"
#include "Pin_Voltage.h"
#include "Sample_Clock.h"
#include "isr_1.h"
#include "Pin_Current_aliases.h"
#include "Pin_Current.h"
#include "Pin_Load_Current_aliases.h"
#include "Pin_Load_Current.h"
#include "Pin_Torque_aliases.h"
#include "Pin_Torque.h"
#include "UART.h"
#include "isr_2.h"
#include "isr_5.h"
#include "Pin_Speed_aliases.h"
#include "Pin_Speed.h"
#include "Regulation_Clock.h"
#include "isr_3.h"
#include "Log_Clock.h"
#include "isr_4.h"
#include "PWM_Regulering.h"
#include "PWM_Clock.h"
#include "PWM_Out_aliases.h"
#include "PWM_Out.h"
#include "Counter_Speed.h"
#include "Speed_Clock.h"
#include "PWM_Speed.h"
#include "Counter_Clock.h"
#include "AD_konverter_SAR.h"
#include "AD_konverter_IntClock.h"
#include "AD_konverter_TempBuf_dma.h"
#include "AD_konverter_FinalBuf_dma.h"
#include "AD_konverter_IRQ.h"
#include "UART_IntClock.h"
#include "core_cm3_psoc5.h"
#include "core_cm3.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"

/*[]*/

