/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 SP1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "PWM_motor.h"
#include "Clock_1.h"
#include "Motor_out_aliases.h"
#include "Motor_out.h"
#include "Control_Reg_motor_reset.h"
#include "Timer_RPM.h"
#include "RPM_aliases.h"
#include "RPM.h"
#include "RPM_isr.h"
#include "Motor_Amp_aliases.h"
#include "Motor_Amp.h"
#include "Comp_1.h"
#include "VDAC8_1.h"
#include "Clock_2.h"
#include "Clock_motor.h"
#include "isr_motor.h"
#include "Status_Reg_OverCurrent.h"
#include "RX_1_aliases.h"
#include "RX_1.h"
#include "TX_1_aliases.h"
#include "TX_1.h"
#include "CAN_1.h"
#include "USBUART_1.h"
#include "USBUART_1_audio.h"
#include "USBUART_1_cdc.h"
#include "USBUART_1_hid.h"
#include "USBUART_1_midi.h"
#include "USBUART_1_pvt.h"
#include "USBUART_1_cydmac.h"
#include "USBUART_1_msc.h"
#include "USBUART_1_Dm_aliases.h"
#include "USBUART_1_Dm.h"
#include "USBUART_1_Dp_aliases.h"
#include "USBUART_1_Dp.h"
#include "core_cm3_psoc5.h"
#include "core_cm3.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"

/*[]*/

