/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 CP1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "USBUART_1.h"
#include "USBUART_1_audio.h"
#include "USBUART_1_cdc.h"
#include "USBUART_1_hid.h"
#include "USBUART_1_midi.h"
#include "USBUART_1_pvt.h"
#include "ADC_SAR_Seq_1.h"
#include "Comp_1.h"
#include "Clock_1.h"
#include "V_motor_aliases.h"
#include "V_motor.h"
#include "A_motor_aliases.h"
#include "A_motor.h"
#include "Moment_aliases.h"
#include "Moment.h"
#include "A_generator_aliases.h"
#include "A_generator.h"
#include "PWM_1.h"
#include "VDAC8_1.h"
#include "Clock_2.h"
#include "Control_Reg_1.h"
#include "PWM_belastning_aliases.h"
#include "PWM_belastning.h"
#include "Clock_3.h"
#include "ADC_SAR_1.h"
#include "isr_1.h"
#include "Opamp_1.h"
#include "Timer_1.h"
#include "Counter_1.h"
#include "isr_2.h"
#include "RPM_aliases.h"
#include "RPM.h"
#include "Status_Reg_1.h"
#include "isr_3.h"
#include "Clock_4.h"
#include "isr_4.h"
#include "Clock_5.h"
#include "Counter_2.h"
#include "USBUART_1_Dm_aliases.h"
#include "USBUART_1_Dm.h"
#include "USBUART_1_Dp_aliases.h"
#include "USBUART_1_Dp.h"
#include "ADC_SAR_Seq_1_SAR.h"
#include "ADC_SAR_Seq_1_IntClock.h"
#include "ADC_SAR_Seq_1_TempBuf_dma.h"
#include "ADC_SAR_Seq_1_FinalBuf_dma.h"
#include "ADC_SAR_Seq_1_IRQ.h"
#include "ADC_SAR_1_IRQ.h"
#include "ADC_SAR_1_theACLK.h"
#include "ADC_SAR_Seq_1_SAR_Bypass_aliases.h"
#include "ADC_SAR_Seq_1_SAR_Bypass.h"
#include "core_cm3_psoc5.h"
#include "core_cm3.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"

/*[]*/

